### ISSUE TITLE
Tidy up namespaces

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#57] opened 2018-10-20 13:24 UTC
The proliferation of sub-namespaces of lf::mesh is rather a nuisance than a benefit.
- Finally remove all facilities of mesh::hybrid2d; not really maintained anymore.
- Get rid of namespaces/folders mesh::hybriod2dp, mesh::utils, mesh::test_utils: Move all functions/files relying on Google Test to the test folder/a namespace lf::mesh::test, all others to lf::mesh.
- Rename mesh::hybrid2dp::Mesh -> mesh::Hybrid2DMesh, mesh::hybrid2dp::MeshFactory -> mesh::Hybriod2DMeshFactory

I hope an IDE can render such reorganization tractable.

The general namespace arrangement for the library should be 'lf' as top level, `lf::*` as implementation level, and `lf::*::test` for the unit tests.

**Comment by craffael** [comment] 2018-10-21 18:09
> 
> 
> The proliferation of sub-namespaces of lf::mesh is rather a nuisance than a benefit.
> 
>     * Finally remove all facilities of mesh::hybrid2d; not really maintained anymore.

I agree and I will remove the `lf::mesh::hybrid2d` module and replace all occurences with the `lf::mesh::hybrid2dp` mesh manager. We could also think about renaming `hybrid2dp` to `hybrid2d`...

>     * Get rid of namespaces/folders mesh::hybriod2dp, mesh::utils, mesh::test_utils: Move all functions/files relying on Google Test to the test folder/a namespace lf::mesh::test, all others to lf::mesh.

I don't agree that sub-namespaces are necessarily bad. After all, a namespace hierarchy allows us to group similar classes/functions together. The standard library (e.g. `std::chrono::*`) and boost (e.g. `boost::spirit::ascii::*` ) use it for this purpose. On the other hand, it's true that there is some controversy around having deeply nested namespaces. The argument against nested namespaces is is usually, that it is too complicated to write out the full name.


In the concrete example of the mesh namespace, (sub-)namespaces allow us to give __additional meaning__ that would otherwise be lost:
- Classes in `lf::mesh` define the abstract mesh manager. They are all interface classes (I suggest to move builders to the `lf::mesh::utils` namespace).
- `lf::mesh::hybrid2dp` contains classes that make up a mesh manager for 2D hybrid meshes.
- `lf::mesh::utils` contains classes/functions that work on general mesh managers (as they are defined in `lf::mesh`)

On the other hand, sub-namespaces lead to longer names. But in this case the effect is rather small as it essentially amounts to introducing a `::` in `Hybrid2DMesh` and `Hybrid2DMeshFactory`. One could argue that one saves many additional characters by moving the `lf::mesh::hybrid2dp::Point` (and other classes) classes into `lf::mesh`. However this is only partially true: If we decide to add another mesh manager for fully 3D meshes in the future, this mesh manager will likely bring his own specialization of `Point` and in order to avoid name clashes we would have name this class `Hybrid3DPoint`. Ergo, we should also rename `Point` -> `Hybrid2DPoint`.

I think the mesh module is a special case because it contains a set of classes which together make up an interface. Everytime we implement this interface (hybrid2dp), we have to provide a whole set of classes with similar names which naturally leads to name clashes. I think nested namespaces are a nice way for resolving this problem.

It's true that all other modules of  LehrFEM++ do not introduce sub namespaces. But I would not make a rule out of this and enforce it on the mesh module only to save 2 characters.

I also want to point out that at the moment there is a [one-to-one relationship between namespaces, cmake-targets and folders.](https://craffael.github.io/lehrfempp/modules_.html). So moving the content from `lf::mesh::test_utils` to `lf::mesh::test` would consequently mean that we would give up the cmake target `lf.mesh.test_utils` in favor of the cmake target `lf.mesh.test`. The problem is that `lf.mesh.test_utils` is a _library_ target (so it can be included in other executable targets) whereas `lf.mesh.test` is an _executable_ target. Hence, it is still necessary to keep a `lf.mesh.test_utils` target and it would be natural to also keep the corresponding folder and namespace...

**Comment by hiptmair** [comment] 2018-10-21 18:37
The points raised above are valid. In particular, I failed to take into account the relationship between Cmake targets, namespaces and folders. This would be lost after refactoring, which is definitely not desirable. So let us keep the current structure for good.

**Comment by craffael** [comment] 2018-10-21 19:07
Okay good. I will remove the `hybrid2d` namespace and rename `hybrid2dp` -> `hybrid2d` probably on Tuesday evening. I will probably send out an email to all collaborators after it's done so they can merge the master branch into their current working branch in order to prevent too many merge conflicts.

**Comment by hiptmair** [comment] 2018-10-29 04:39
No change to namespace layout.

**Closed** 2018-10-29 04:39 UTC
Labels: design
